[programs.localnet]
lottery = "WEBL9KJ2NVCTqvxE4Vz6jAuWudi6VaTQsxKCjeHFoAB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/.config/solana/wedp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000